"""Draw every figure and write the frontier table from results/summary.json.

Figures go to results/figs/, the tables to results/frontier_table.tex and
results/seed_table.tex.

    python3 make_figs.py [results_dir]
"""
import json, os, sys
import numpy as np
import figures
from analyse import pivot

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results")
FIGS = os.path.join(RES, "figs")


def main():
    figures.use_style()
    os.makedirs(FIGS, exist_ok=True)
    S = json.load(open(os.path.join(RES, "summary.json")))
    integ = json.load(open(os.path.join(RES, "integrity.json")))["beef"]["detail"]

    figures.fig_integrity(os.path.join(FIGS, "fig1_integrity.pdf"),
                          integ, S["integrity_recheck"], S["contamination"])
    print("fig 1")

    figures.fig_frontier(os.path.join(FIGS, "fig2_frontier.pdf"),
                         S["frontier"], S["calf"]["frontier"],
                         S["teacher"]["macro_f1"], S["calf"]["teacher"],
                         S["majority_f1"], S["calf"]["majority_f1"])
    print("fig 2")

    piv = pivot(json.load(open(os.path.join(RES, "frontier.json")))["rows"])
    per_animal = {k: np.array([c[k] - c["scratch"] for c in piv.values()])
                  for k in ("prune", "distil")}
    seeds = {k: v["prune_gain_by_kb"] for k, v in S["seeds"].items() if "prune_gain_by_kb" in v}
    equal = {k: v["prune_gain_by_kb"] for k, v in S.get("equal_schedule", {}).items()}
    figures.fig_paired(os.path.join(FIGS, "fig3_paired.pdf"), per_animal,
                       seeds, S["calf"]["paired"]["prune"]["mean"],
                       S["between_animal_sd"], equal)
    print("fig 3")

    figures.fig_decomposition(os.path.join(FIGS, "fig4_decomposition.pdf"),
                              S["decomposition"], S["calf"]["capacity_deficit"])
    print("fig 4")

    # the frontier table, generated rather than typed
    def th(n):
        """Thousands separator LaTeX will not break across the column."""
        return f"{n:,}".replace(",", "{,}")

    t = [r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
         r"Widths & params & KB & pruning & distillation & same size \\", r"\midrule"]
    for r in S["frontier"]:
        w = r["widths"]
        if "scratch" not in r:
            t.append(f"{w} & {th(r['params'])} & {r['kb']:.1f} & "
                     r"\multicolumn{3}{c}{teacher, "
                     + f"{S['teacher']['macro_f1']:.3f}" + r"} \\")
            t.append(r"\addlinespace")
            continue
        t.append(f"{w} & {th(r['params'])} & {r['kb']:.2f} & "
                 f"{r['prune']:.3f} & {r['distil']:.3f} & {r['scratch']:.3f} \\\\")
    t += [r"\bottomrule", r"\end{tabular}"]
    with open(os.path.join(RES, "frontier_table.tex"), "w") as fh:
        fh.write("% generated by make_figs.py -- do not edit\n" + "\n".join(t) + "\n")
    print("wrote frontier_table.tex")
    seed_table(S)


def _diff(d):
    """Mean paired difference and its paired t-test p-value, for a table cell."""
    m = f"{d['mean']:+.4f}".replace("-", r"\ensuremath{-}")
    pv = d["p_t"]
    ps = f"{pv:.3f}" if pv >= 0.001 else r"{<}\,0.001"
    return f"{m} ({ps})"


def seed_table(S):
    """Per-seed paired differences against the same-size control, both pruning
    schedules and both datasets, written to results/seed_table.tex."""
    seeds, equal = S["seeds"], S.get("equal_schedule", {})
    t = [r"\begin{tabular}{@{}llllcl@{}}", r"\toprule",
         r"& beef & \multicolumn{3}{c}{beef, pruning} & calf \\",
         r"\cmidrule(lr){2-2}\cmidrule(lr){3-5}\cmidrule(l){6-6}",
         r"Seed & distillation & standard & equal schedule & collapses & pruning \\",
         r"\midrule"]
    for k in sorted(seeds, key=int):
        v = seeds[k]
        if "paired" not in v:
            continue
        e = equal.get(k)
        eq = _diff(e["paired"]["prune"]) if e else "not run"
        col = str(len(v["prune_collapses"])) + (f" / {len(e['prune_collapses'])}" if e else "")
        calf = _diff(v["calf"]["paired"]["prune"]) if "calf" in v else "not run"
        t.append(f"{k} & {_diff(v['paired']['distil'])} & {_diff(v['paired']['prune'])} & "
                 f"{eq} & {col} & {calf} \\\\")
    t += [r"\bottomrule", r"\end{tabular}"]
    with open(os.path.join(RES, "seed_table.tex"), "w") as fh:
        fh.write("% generated by make_figs.py -- do not edit\n" + "\n".join(t) + "\n")
    print("wrote seed_table.tex")


if __name__ == "__main__":
    main()
